env:
   global:
     - CONAN_USERNAME: "{{ conan_username }}"
     - CONAN_LOGIN_USERNAME: "{{ conan_login_username }}"
     - CONAN_CHANNEL: "{{ conan_channel }}"
     - CONAN_UPLOAD: "{{ conan_upload }}"
     - CONAN_STABLE_BRANCH_PATTERN: "(release|stable)/*"
     - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1 # Will only upload when the branch matches the stable pattern
     - CONAN_DOCKER_32_IMAGES: 1
     - CONAN_TOTAL_PAGES: {{ total_pages|default(1) }}
{% if build_policy %}     - CONAN_BUILD_POLICY: {{ build_policy }}{% endif %}

linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic

stages:
  - conan-linux
  - conan-osx

jobs:
   include:
     {% for compiler in gcc_compilers %}{% for page in range(1, total_pages|default(1) + 1) %}
      - <<: *linux
        stage: conan-linux
        env: CONAN_GCC_VERSIONS={{ compiler.version }} CONAN_DOCKER_IMAGE={{ compiler.docker_image }} CONAN_CURRENT_PAGE={{ page }}
     {% endfor %}{% endfor %}

     {% for compiler in clang_compilers %}{% for page in range(1, total_pages|default(1) + 1) %}
      - <<: *linux
        stage: conan-linux
        env: CONAN_CLANG_VERSIONS={{ compiler.version }} CONAN_DOCKER_IMAGE={{ compiler.docker_image }} CONAN_CURRENT_PAGE={{ page }}
     {% endfor %}{% endfor %}

     {% for compiler in apple_clang_compilers %}{% for page in range(1, total_pages|default(1) + 1) %}
      - <<: *linux
        stage: conan-osx
        osx_image: {{ compiler.osx_image }}
        env: CONAN_APPLE_CLANG_VERSIONS={{ compiler.version }} CONAN_CURRENT_PAGE={{ page }}
     {% endfor %}{% endfor %}

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
