build: false


environment:
    PYTHON: "C:\\Python37"

    CONAN_USERNAME: "{{ conan_username }}"
    CONAN_LOGIN_USERNAME: "{{ conan_login_username }}"
    CONAN_CHANNEL: "{{ conan_channel }}"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
    CONAN_UPLOAD: "{{ conan_upload }}"
    CONAN_STABLE_BRANCH_PATTERN: "(release|stable)/*"
    CONAN_UPLOAD_ONLY_WHEN_STABLE: 1 # Will only upload when the branch matches stable pattern
    CONAN_TOTAL_PAGES: {{ total_pages|default(1) }}
{% if build_policy %}    CONAN_BUILD_POLICY: {{ build_policy }}{% endif %}

    matrix:
      {% for compiler in visual_compilers %}{% for page in range(1, total_pages|default(1) + 1) %}
        - APPVEYOR_BUILD_WORKER_IMAGE: {{ compiler.worker_image }}
          CONAN_VISUAL_VERSIONS: {{ compiler.version }}
          CONAN_ARCHS: {{ compiler.arch }}
          CONAN_BUILD_TYPES: {{ compiler.build_type }}
          CONAN_VISUAL_RUNTIMES: {{ compiler.runtime }}
          CONAN_CURRENT_PAGE: {{ page }}
      {% endfor %}{% endfor %}
      {% for configuration in mingw_configurations %}{% for page in range(1, total_pages|default(1) + 1) %}
        - MINGW_CONFIGURATIONS: "{{ configuration }}"
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
          CONAN_CURRENT_PAGE: {{ page }}
      {% endfor %}{% endfor %}

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
