repository:
  # name: repo-name
  description: {{ recipe.description }}
  homepage: {{ recipe.homepage }}
  # default_branch: master
  topics: {{ ', '.join(recipe.get_topics()) }}

  private: false
  has_issues: false
  has_wiki: false
  has_downloads: false

  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
