language: python
python:
  - "3.6"

#safelist
branches:
  only:
  - dev

# command to install dependencies
install:
  - pip install -e .

before_script:
  - .travis/before_script.sh

# command to run tests
script:
  - conan_community_web --output-path=../tmp --force examples/conan_community_web.yml

after_success:
  - .travis/after_success.sh
